
name = "pour-bien-vivre-ensemble"
main = "src/index.tsx"
compatibility_date = "2023-10-14"

[[kv_namespaces]]
binding = "GALERIE_DATA"
id = "42da596772d84aa3bbf313755fca2fde"

[[kv_namespaces]]
binding = "REALISATIONS_DATA"
id = "66a3c6babc1d4867bd97f5d90b31a454"

[[d1_databases]]
binding = "DB"
database_name = "pbve-realisations"
database_id = "4df393c3-fce6-4254-a126-322234cf6d07"
